### ISSUE TITLE
Fails on Python v3.10 and higher

### ISSUE THREAD

**Issue by leo0liver** [giocaizzi/pysurfline#2]
Hey, great work on this :)

I've noticed that the module doesn't work on versions of python newer than version 3.10.
The following error is produced:
`AttributeError: module 'collections' has no attribute 'MutableMapping'`

This is occurring because `collections.MutableMappings` was replaced with `collections.abc.MutableMappings` in Python 3.10.

A quick and easy way this could be fixed, is by updating `utils.py` to import the new version when being run from newer versions of Python like this:
```
if sys.version_info.major == 3 and sys.version_info.minor >= 10:
    from collections.abc import MutableMapping
else:
    from collections import MutableMapping
```

**Comment by giocaizzi** [comment]
thanks a lot for finding this out!

i am actually struggling to test the package on multiple version with Actions and locally i am using 3.9, so i never noticed.

I will add this in the next days 🚀

**Comment by giocaizzi** [comment]
fixed, i will release the version soon. 
I will make some little refinements to the api.
thanks!

**Comment by leo0liver** [comment]
awesome :)
thanks!
